[package]
name = "typso"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Sylvan Franklin"]
license = "MIT"
description = "Make custom bingo boards in Typst "

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
